#!/bin/bash

# Following https://www.raspberrypi.org/forums/viewtopic.php?t=224423

# light led while Wi-Fi is connected
if [[ ! -d /sys/class/gpio/gpio12/ ]]
then
  echo 12 > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio12/direction
fi
case "$reason" in
CARRIER)
  echo 1 > /sys/class/gpio/gpio12/value
   ;;
 NOCARRIER)
  echo 0 > /sys/class/gpio/gpio12/value
   ;;
esac
