#!/bin/bash
echo 'Installing kiln-controller and all dependencies'

# get the path of the script:
SCRIPT_PATH="`dirname \"$0\"`"                  # relative
SCRIPT_PATH="`( cd \"$SCRIPT_PATH\" && pwd )`"  # absolutized and normalized
if [ -z "$SCRIPT_PATH" ] ; then
  exit 1
fi
cd $SCRIPT_PATH
cd ..

# install python:
sudo apt-get install build-essential python3-pip python3-dev python3-virtualenv libevent-dev virtualenv -y

# install numpy and matplotlib:
sudo apt-get install libblas-dev liblapack-dev libatlas3-base -y
sudo apt-get install python3-numpy python3-matplotlib -y

# create and go to the virtual environment:
virtualenv -p python3 venv
source venv/bin/activate

# install all python packages we need:
pip3 install --upgrade setuptools
pip3 install -r requirements.txt

# install what we need to be on the internet:
wget https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-armv6l.tar.xz
tar xvf node-v10.15.3-linux-armv6l.tar.xz
cd node-v10.15.3-linux-armv6l
sudo cp -R bin/* /usr/bin/
sudo cp -R lib/* /usr/lib/
sudo apt-get update && sudo apt-get upgrade
sudo npm install -g localtunnel
cd ..
rm -rf node-v10.15.3-linux-armv6l node-v10.15.3-linux-armv6l.tar.xz

# create the credential file:
touch mail_credentials.txt
touch log_credentials.txt
