#!/bin/bash

# get the path of the script:
SCRIPT_PATH="`dirname \"$0\"`"                  # relative
SCRIPT_PATH="`( cd \"$SCRIPT_PATH\" && pwd )`"  # absolutized and normalized
if [ -z "$SCRIPT_PATH" ] ; then
  exit 1
fi
cd $SCRIPT_PATH
BASEDIR=$SCRIPT_PATH/..

# write the service:
cat <<EOF > /etc/systemd/system/led-controller.service

[Unit]
Description=led-controller

[Service]
Restart=always
ExecStart=$BASEDIR/venv/bin/python $BASEDIR/script/light_controller.py

[Install]
WantedBy=multi-user.target

EOF

# start service now:
sudo systemctl start led-controller.service
# on boot:
sudo systemctl enable led-controller.service
