#!/bin/bash

# get wi-fi state:
state=$(cat /sys/class/net/wlan0/operstate)

# if state is up we light the led, otherwise we turn it off and try to restart Wi-Fi
if [ $state = "up" ]; then
  curl -X POST -H "Content-Type: application/json" -d '{"1": "(0,0,255)"}' http://0.0.0.0:5001
else
  curl -X POST -H "Content-Type: application/json" -d '{"1": "(0,0,0)"}' http://0.0.0.0:5001
  ip link set wlan0 up
fi;
