#!/bin/bash

# light led while Wi-Fi is connected
if [[ ! -d /sys/class/gpio/gpio32/ ]]
then
  echo 32 > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio32/direction
fi
case "$reason" in
CARRIER)
  echo 1 > /sys/class/gpio/gpio32/value
   ;;
 NOCARRIER)
  echo 0 > /sys/class/gpio/gpio32/value
   ;;
esac
