#!/bin/bash

# get the path of the script:
SCRIPT_PATH="`dirname \"$0\"`"                  # relative
SCRIPT_PATH="`( cd \"$SCRIPT_PATH\" && pwd )`"  # absolutized and normalized
if [ -z "$SCRIPT_PATH" ] ; then
  exit 1
fi

# now copy the web hook to the position it has to have:
cp $SCRIPT_PATH/05-wifiled /lib/dhcpcd/dhcpcd-hooks/
