#!/bin/bash

# enable light led while Wi-Fi is connected
if [[ ! -d /sys/class/gpio/gpio12/ ]]
then
  echo 12 > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio12/direction
fi

# get wi-fi state:
state=$(cat /sys/class/net/wlan0/operstate)

# if state is up we light the led, otherwise we turn it off and try to restart Wi-Fi
if [ $state = "up" ]; then
  echo 1 > /sys/class/gpio/gpio27/value
else
  echo 0 > /sys/class/gpio/gpio27/value
  ip link set wlan0 up
fi;
